### ISSUE TITLE
config-resource deployment error

### ISSUE THREAD

**Issue by mocenas** [snowdrop/spring-boot-istio-security-booster#27]
Deploying the `block-greeting-service.yml` rule with the arquillian istioAssistant causes program to throw and exception

```
java.lang.IllegalArgumentException: Cannot load class: me.snowdrop.istio.api.model.v1.routing.Rule
	at me.snowdrop.istio.booster.security.OpenshiftIT.deployRouteRule(OpenshiftIT.java:51)
```

Code that produces this error is present at:
https://github.com/mocenas/spring-boot-istio-security-booster/tree/istio_error
and can be launched in empty namespace by:

```
mvn clean verify -Popenshift,openshift-it
```

**Comment by mocenas** [comment]
@geoand That is the entire stack trace (pasted before) - I was not able to dig out more of it.

**Comment by geoand** [comment]
Ok, thanks!

**Comment by geoand** [comment]
The PR I have opened in the Istio Java API we help get passed the exception you are seeing @mocenas.

However there is still a problem with the Istio Java API when 

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denynameservicerequest
spec:
```

is  loaded because the `spec` part is empty

**Comment by mocenas** [comment]
I think that this is rather your call to decide. But I would prefer solution 1 - Generally it would be good, if Java API can handle the istio resources in same way as oc client.

**Comment by geoand** [comment]
@mocenas Indeed that is the best solution. @metacosm and I will have to look at this closely

**Comment by geoand** [comment]
@gytis Would it be possible to provide some default configuration in the `spec` section of

```
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denynameservicerequest
spec:
```

in `block-greeting-service.yml`? Currently it's causing problems in the tests due to a limitation in the Istio Java API

**Comment by gytis** [comment]
@geoand I'm sure we can add something. I guess metadata or something similar might do it. However, I'd prefer to keep it minimal and remove it whenever the Java API is fixed.

**Comment by geoand** [comment]
Ideally yes, it should be as minimal as possible. Currently the Istio Java API fails (with a NPE) I think because the spec is empty. @metacosm have you been able to check this at all?

**Comment by geoand** [comment]
We should now have the pieces in place in the Istio Java API to get past this issue.
So we should revisit once the next release is out

**Comment by metacosm** [comment]
Istio Java API 0.12 is out.

**Comment by geoand** [comment]
I have issued a PR to Arquillian Cube, once that is merged we can fix this issue
